### ISSUE TITLE
Error when trying to enable module through drush

### ISSUE THREAD

**Issue by gabe-morales** [makhnovskiy/YouTube-Import-Drupal-8#3]
While the module seems to have installed correctly, drush outputs a parse error when trying to read one of your YAML files. The source of the problem seems to be your _youtube_import.routing.yml_, where "defaults:" on line 18 is not indented correctly.

**Comment by MANTENN** [comment]
Can you paste in your YAML file, or attach it?

**Comment by gabe-morales** [comment]
Sure, although there seem to be other errors still after this fix.

This is the end of the file:
```
help.page.youtube_import:
  path: '/admin/help/youtube_import'
  defaults:
    _title: 'Youtube Import'
    _title_context: 'Setup Page.'
    _controller: '\Drupal\youtube_import\Controller\youtube_import_run::hook_help'
```
